const data = [
    {
        id: 4799,
        first_name: 'Trung Duc',
        last_name: 'Nguyen',
        full_name: 'Trung Duc Nguyen',
        nickname: 'baby4ever11',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/4799/63ebb969941a9.jpg',
        bio: 'hi anh em',
        tick: false,
        followings_count: 16,
        followers_count: 9,
        likes_count: 23,
        website_url: 'https://www.facebook.com/lengoc.thai.5',
        facebook_url: 'https://www.facebook.com/lengoc.thai.5',
        youtube_url: '',
        twitter_url: '',
        instagram_url: '',
        created_at: '2023-01-03 14:15:00',
        updated_at: '2023-05-16 00:44:58',
    },
    {
        id: 211,
        first_name: 'Đỗ',
        last_name: 'Xuân Bách',
        full_name: 'Đỗ Xuân Bách',
        nickname: 'xuanbachdev',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/211/63c12e11ab47e.jpg',
        bio: 'Xuanbach.dev',
        tick: false,
        followings_count: 7,
        followers_count: 86,
        likes_count: 26,
        website_url: 'https://fullstack.edu.vn/',
        facebook_url: 'https://www.facebook.com/xuanbachh.dev',
        youtube_url: '',
        twitter_url: '',
        instagram_url: '',
        created_at: '2022-09-11 12:25:57',
        updated_at: '2023-07-12 14:33:25',
    },
    {
        id: 89,
        first_name: 'Vo',
        last_name: 'Chau Vuong',
        full_name: 'Vo Chau Vuong',
        nickname: 'chauvuongvo',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/',
        bio: '✨ 1998 ✨\nVietnam 🇻🇳\nĐỪNG LẤY VIDEO CỦA TÔI ĐI SO SÁNH NỮA. XIN HÃY TÔN TRỌNG !',
        tick: false,
        followings_count: 26,
        followers_count: 8,
        likes_count: 24,
        website_url: 'https://fullstack.edu.vn/',
        facebook_url: '',
        youtube_url: '',
        twitter_url: '',
        instagram_url: '',
        created_at: '2022-08-22 00:14:16',
        updated_at: '2023-06-17 21:32:18',
    },
    {
        id: 135,
        first_name: 'Mr',
        last_name: 'Quynh',
        full_name: 'Mr Quynh',
        nickname: 'quynhnv',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/135/644ff9926da0a.jpg',
        bio: '✨ 2000 ✨\r\nNothing is impossible',
        tick: false,
        followings_count: 22,
        followers_count: 9,
        likes_count: 24,
        website_url: 'https://fullstack.edu.vn/',
        facebook_url: '',
        youtube_url: '',
        twitter_url: '',
        instagram_url: '',
        created_at: '2022-08-24 08:24:48',
        updated_at: '2023-07-13 11:41:11',
    },
    {
        id: 272,
        first_name: 'Long',
        last_name: 'Vu',
        full_name: 'Long Vu',
        nickname: 'long0611',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/272/6336641299be6.png',
        bio: '...',
        tick: false,
        followings_count: 9,
        followers_count: 3,
        likes_count: 5,
        website_url: 'https://fullstack.edu.vn/',
        facebook_url: '',
        youtube_url: '',
        twitter_url: '',
        instagram_url: '',
        created_at: '2022-09-30 10:31:24',
        updated_at: '2022-12-06 09:33:24',
    },
    {
        id: 5167,
        first_name: 'Mr',
        last_name: 'Birdy',
        full_name: 'Mr Birdy',
        nickname: 'anhbui01vn',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/5167/63f97a1f7015c.jpg',
        bio: 'Main my account. Follow me to watch at lease video!',
        tick: false,
        followings_count: 5,
        followers_count: 3,
        likes_count: 11,
        website_url: '',
        facebook_url: '',
        youtube_url: '',
        twitter_url: '',
        instagram_url: '',
        created_at: '2023-02-25 09:55:40',
        updated_at: '2023-07-11 20:02:00',
    },
    {
        id: 3881,
        first_name: 'Nguyễn',
        last_name: 'Duy Vụ',
        full_name: 'Nguyễn Duy Vụ',
        nickname: 'duyvu2612003',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/3881/633ed00c94728.jpg',
        bio: 'Lật đổ top top cùng duyVu',
        tick: false,
        followings_count: 13,
        followers_count: 28,
        likes_count: 14,
        website_url: 'https://duyvu-toptop.vercel.app/',
        facebook_url: '',
        youtube_url: '',
        twitter_url: '',
        instagram_url: '',
        created_at: '2022-10-06 19:47:36',
        updated_at: '2023-05-12 12:28:25',
    },
    {
        id: 5280,
        first_name: 'Văn',
        last_name: 'Mạnh',
        full_name: 'Văn Mạnh',
        nickname: 'dongvanmanh280122',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/5280/64192ab0bd684.jpg',
        bio: 'Dong Van Manh 2002',
        tick: false,
        followings_count: 0,
        followers_count: 7,
        likes_count: 14,
        website_url: 'https://fullstack.edu.vn/',
        facebook_url: '',
        youtube_url: '',
        twitter_url: '',
        instagram_url: '',
        created_at: '2023-03-21 10:51:47',
        updated_at: '2023-07-07 22:36:15',
    },
    {
        id: 128,
        first_name: 'Nguyễn',
        last_name: 'Vũ',
        full_name: 'Nguyễn Vũ',
        nickname: 'nguyenleavu',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/128/631ed5ebb418a.jpg',
        bio: '✨ 1999 ✨',
        tick: false,
        followings_count: 18,
        followers_count: 4,
        likes_count: 11,
        website_url: 'https://fullstack.edu.vn/',
        facebook_url: '',
        youtube_url: '',
        twitter_url: '',
        instagram_url: '',
        created_at: '2022-08-23 10:28:53',
        updated_at: '2023-07-13 11:40:38',
    },
    {
        id: 148,
        first_name: 'Vita',
        last_name: 'min C',
        full_name: 'Vita min C',
        nickname: 'meokhung2905',
        avatar: 'https://files.fullstack.edu.vn/f8-tiktok/users/148/641cf95f01d3d.jpg',
        bio: '✨1998✨ Vietnam 🇻🇳 ĐỪNG LẤY VIDEO CỦA TÔI ĐI SO SÁNH NỮA. XIN HÃY TÔN TRỌNG !',
        tick: false,
        followings_count: 9,
        followers_count: 5,
        likes_count: 10,
        website_url: 'https://fullstack.edu.vn/',
        facebook_url: 'https://facebook.com/meomeo',
        youtube_url: 'https://youtube.com/meome',
        twitter_url: 'https://twitter.com/meomeo',
        instagram_url: 'https://instagram.com/meomeo',
        created_at: '2022-08-25 22:17:59',
        updated_at: '2023-05-17 22:45:20',
    },
];

export default data;
